#!/bin/bash

echo "==================================="
echo "ChatGPT Q&A Agent - Setup Instructions"
echo "==================================="
echo ""
echo "To use this app with ChatGPT, follow these steps:"
echo ""
echo "1. Make sure the server is running:"
echo "   npm start"
echo ""
echo "2. In ChatGPT, go to Settings"
echo ""
echo "3. Click on 'GPT Actions' or 'Actions'"
echo ""
echo "4. Enable **Developer Mode**"
echo ""
echo "5. Add a new action with this URL:"
echo "   http://localhost:3001/mcp"
echo ""
echo "6. If deploying to production, use your public URL instead"
echo "   (e.g., https://yourdomain.com/mcp)"
echo ""
echo "7. Save the action"
echo ""
echo "8. Try asking ChatGPT:"
echo "   - 'Recommend me chinos for work'"
echo "   - 'Help me find a laptop'"
echo "   - 'I need a new backpack'"
echo ""
echo "==================================="
echo "Current Configuration:"
echo "  Questions: ${NUM_QUESTIONS:-3}"
echo "  Answers per question: ${NUM_ANSWERS:-4}"
echo "  Server Port: ${PORT:-3001}"
echo "==================================="


